### ISSUE TITLE
Changing Start or End icon URL breaks mouseout Leaflet event

### ISSUE THREAD

**Issue by HugoMaffre** [mpetazzoni/leaflet-gpx#101]
Hello,

Thank you for your plugin, I use it (and like it) a lot.
I recently had an issue with the mouseout leaflet event and changing startIconUrl or endIconUrl.
In the code below, sometimes (particulary if you move the mouse fast), the mouseout event is not triggered.
If I remove the lines concerning the icons, the mouseout event fires normally.

```
gpx.on('mouseover', function (e) {
    var layer = e.target;
    layer.options.marker_options.startIconUrl = 'myHoverIconStartUrl';
    layer.options.marker_options.endIconUrl = 'myHoverIconEndUrl';
    layer.reload();
});
gpx.on('mouseout', function (e) {
    console.log('Mouse out !')
    var layer = e.target;
    layer.options.marker_options.startIconUrl = '';
    layer.options.marker_options.endIconUrl = '';
    /* this line below causes the issue */
    layer.reload();
});
```

Displaying start and end icons on hover is probably a common thing to do with leaflet-gpx.
Maybe there is something I simply do wrong, feel free to add the "question" label in this case.

EDIT : Apparently, it is the layer.reload() that causes the problem. It causes some flickering on reloading and triggers mouseover and mouseout multiple times. So the question would now be : Is it possible to change startIconUrl and endIconUrl without reloading the layer ?

Thank you for your help

**Comment by mpetazzoni** [comment]
Hmm, yeah I definitely would not use `layer.reload()` to achieve this. `L.GPX` will fire up events for each marker it adds, including the start and end markers; see:

* https://github.com/mpetazzoni/leaflet-gpx/blob/main/gpx.js#L543
* https://github.com/mpetazzoni/leaflet-gpx/blob/main/gpx.js#L553

I recommend you grab a reference to the `L.Marker` objects from those events, and show/hide _those_ instead as necessary.
