### ISSUE TITLE
I couldn't see a way to disable marker icons for the start and end points. 

### ISSUE THREAD

**Issue by kreativejuices** [mpetazzoni/leaflet-gpx#102]
Love this plugin, just couldn't see any way to disable the start and end markers. I only wanted the polyline to be shown. So i tried this,

marker_options: {
    startIconUrl: '',
    endIconUrl: '',
    shadowUrl: ''
  }

It does the job but wondered if there was a better way to do this?

Thanks! :)

**Comment by mpetazzoni** [comment]
That's the way; a slightly cleaner version is to set them to `null` instead of an empty string. The code just checks for "falsy":

```js
if (options.marker_options.startIcon || options.marker_options.startIconUrl) {
```

https://github.com/mpetazzoni/leaflet-gpx/blob/main/gpx.js#L537-L554

**Comment by luckykamon** [comment]
> That's the way; a slightly cleaner version is to set them to `null` instead of an empty string. The code just checks for "falsy":
> 
> if (options.marker_options.startIcon || options.marker_options.startIconUrl) {
> https://github.com/mpetazzoni/leaflet-gpx/blob/main/gpx.js#L537-L554

Thanks, now on leaflet-gpx 2.1.2: https://github.com/mpetazzoni/leaflet-gpx/blob/main/gpx.js#L615-L623

```javascript
new L.GPX('/path/to/file.gpx', {
        async: true,
        markers: {
            startIcon: null,
            endIcon: null,
            shadow: null
        }
    }).addTo(map);
```
