### ISSUE TITLE
Point matchers don't work

### ISSUE THREAD

**Issue by vmaysov** [mpetazzoni/leaflet-gpx#106]
Hi there!

My gpx track has named point:
...
`
<wpt lat="44.421723" lon="34.030495">
    <ele>325.63</ele>
    <time>2020-10-18T09:48:17.000Z</time>
    <name>Old</name>
    <desc>...</desc>
  </wpt>
`
...

But this code doesn't change its icon:

`const track = new L.GPX('link to gpx-track', {
    async: true,
    marker_options: {
    pointMatchers: [
      {
        regex: /Old/i,
        icon: new L.icon({
          iconUrl: '/public/img/teh/start.svg'
        })
      }
    ]
  }
}).on('loaded', function(e) {
  map.fitBounds(e.target.getBounds());
}).addTo(map);`

What am I doing wrong?

**Comment by mpetazzoni** [comment]
Ah, because I didn't implement that logic on waypoints, only regular points. Let me fix that!

**Comment by mpetazzoni** [comment]
Release v1.5.1 with the fix.
