### ISSUE TITLE
Elevation gain/loss computation should ignore points with no elevation data (instead of assuming 0)

### ISSUE THREAD

**Issue by andre92160** [mpetazzoni/leaflet-gpx#110]
Hello,
I use leaflet-gpx and I have an issue: get_distance() doesn't give allways the good result:

I join a zipped folder with my script and some gpx to visualize the issue.

get_distance() gives the good distance (12 km) for the track SSS.gpx.
I changed a bit this track and added some waypoints, which gives SSS_wpt.gpx.
get_distance() gives now 18 km, which is wrong.

I loaded SSS_wpt.gpx in Visorando or VisuGpx: they both give the good result: 12 km.

I tried to remove all the waypoints, which gives SSS_wpt2.gpx but get_distance() gives allways a bad result: 18 km.

In fact elevation_gain() and elevation_loss() give also the good results for SSS.gpx and bad results with SSS_wpt.gpx.

NB: To visualize a track (for example SSS.gpx), you need to type: carte.html?track=gpx/SSS.gpx

Regards,
André

[folder_issue.zip](https://github.com/mpetazzoni/leaflet-gpx/files/6287353/folder_issue.zip)

**Comment by andre92160** [comment]
The problem is related with the elements <ele> of the gpx file as it can be seen from the two join gpx files.
<ele> gives the elevation of the point.
[test.zip](https://github.com/mpetazzoni/leaflet-gpx/files/6298548/test.zip)
It's the same track in the two files. The computed distance (260 m) is correct for test.gpx but not in test2.gpx (11 km).
The difference is that in test2.gpx I've deleted some <ele> elements.

I suppose that you consider the elevation is equal to zero when there is no <ele> element; so there is a big difference of altitude.
You should ignore the elevation when <ele> is not present.

Thanks for your work,
André

**Comment by mpetazzoni** [comment]
It's difficult to compute a good and accurate distance from a GPX without a much more complex algorithm. I can look into the elevation gain/loss thing though.
