### ISSUE TITLE
What's wrong with this GPX?

### ISSUE THREAD

**Issue by oe8bck** [mpetazzoni/leaflet-gpx#114]
Loading this GPX file (https://www.oe8bck.at/karte/GPX/206473_Nachbarschaft_Radl.gpx) triggers this error in the console:

gpx.min.js:formatted:310 Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
    at i._parse_gpx_data (gpx.min.js:formatted:310)
    at i (gpx.min.js:formatted:293)
    at XMLHttpRequest.o.onreadystatechange (gpx.min.js:formatted:286)

What's wrong with this file?

Thanks for any answer!
Chrsitof

**Comment by ibrierley** [comment]
You haven't got a closing gpx </gpx> on the doc.

**Comment by oe8bck** [comment]
Thanks for the hint, in the mean-time I found it by myself. Just a lunch break and then a new look on the file and then I saw it. Changed it and now it renders nicely!
