### ISSUE TITLE
gpx layer crams the map when using flyTo()

### ISSUE THREAD

**Issue by ztzthu** [mpetazzoni/leaflet-gpx#119]
Hi, I tried to add a gpx layer then flyTo a place near the gpx layer, using the flyTo function defined by leaflet.

Then I observed that the gpx layer fills up all the map window when the map is zoomed in.

A example code is as follows: https://jsfiddle.net/73945Lcn/2/

Is there a way to avoid this happening? Seems that the gpx layer is also zoomed in or out during the flyto process (which is different from the behaviour of a marker).

Thank you.

**Comment by mpetazzoni** [comment]
This is an expected behavior of animations in Leaflet, see https://github.com/Leaflet/Leaflet/pull/3278#issuecomment-103611919 for the decision.
