### ISSUE TITLE
failed to load track without elevation 

### ISSUE THREAD

**Issue by philippe-queinnec** [mpetazzoni/leaflet-gpx#127]
If a track has no elevation (<ele> tag), or if the first point of a track has no elevation, loading fails.
The culprit is line 488 in _parse_segment. The line
    ll.meta.ele = last.meta.ele;
should be
    if (last != null) { ll.meta.ele = last.meta.ele; }

**Comment by pimschaaf** [comment]
Without this change I get the following error message:
`Uncaught TypeError: Cannot read properties of null (reading 'meta')
    at i._parse_segment (gpx.js:488)`
when elevation data is missing.

**Comment by mpetazzoni** [comment]
Thanks!
