### ISSUE TITLE
Link to demo leads nowhere

### ISSUE THREAD

**Issue by Flugschwein** [mpetazzoni/leaflet-gpx#132]
In the GitHub repository under About, there is a link to http://mpetazzoni.github.com/leaflet-gpx/, which leads to a 404 page. It should be http://mpetazzoni.github.io/leaflet-gpx/ instead.
The GitHub Pages are under the github.io domain, not github.com.
Thanks for the awesome project, I love using it :-)

**Comment by mpetazzoni** [comment]
Good catch! This was fixed in the README recently but not in the repo details. Should be good now!
