### ISSUE TITLE
Color track according to the slope

### ISSUE THREAD

**Issue by boiteasite** [mpetazzoni/leaflet-gpx#138]
Hi,
Is it possible that the color of the track is variable according to the slope ?
For example, blue on the downhill, Red on the uphill, Green on the flat, with a gradient according to the strength of the slope.
Regards

**Comment by mpetazzoni** [comment]
Not directly. `leaflet-gpx` just creates a `L.Polyline` object for the whole track, passing it some optional styling options that you can configure, but this doesn't allow for making the color depend on the slope/incline.

For that, it might require creating many small `L.Polyline` for each part of the track that has contiguous downhill or contiguous uphill, which could lead to serious performance issues for Leaflet. It seems to be what most Leaflet plugin that try to achieve this do though, but I'm not sure how far you'd be able to push it.

**Comment by boiteasite** [comment]
Ah OK, thank you very much for this answer.
