### ISSUE TITLE
Choose multiple GPX via checkbox

### ISSUE THREAD

**Issue by Blittr** [mpetazzoni/leaflet-gpx#139]
Thanks for the very nice project to display a GPX over a leaflet map. I would like to add the possibility to enable or disable multiple GPX via a checkbox. I managed to make a menu to choose from multiple maps (radio button). But I can't manage a selection menu (checkbox) with which I can choose a GPX. I'm afraid I have too basic knowledge of JavaScript. How could I realize this checkbox?

**Comment by jeromectm** [comment]
My [fork](https://github.com/jeromectm/leaflet-gpx/tree/10d68e0f98424a90483518c72401dad37d5a218d) let do this for multiple tracks in a single GPX file, if this can help… I hope it will be merged.

**Comment by mpetazzoni** [comment]
L.GPX is a regular Leaflet layer, so you should be able to instantiate/add them all to the map, and use leaflet's built-in `Control.Layers` (https://leafletjs.com/reference.html#control-layers) to let the user toggle them on/off. All the logic to show/hide them will be handled for you.

**Comment by Blittr** [comment]
Thank you for your reply jeromectm and mpetazzoni 👍. I'm going to study it and hope I can fix it :-)
