### ISSUE TITLE
get_elevation_data() return empty Array

### ISSUE THREAD

**Issue by javanese84** [mpetazzoni/leaflet-gpx#141]
Hi there,

I'm trying to get elevation data from my gpx track, which is like (snippet):
`<trkpt lat="47.398835" lon="10.888071"><ele>990.8</ele><time>2018-11-12T17:45:48Z</time></trkpt>`

But when I'm doing the following, I'm only getting an empty array.

`const leafletGpx = new Leaflet.GPX(
          gpx, {async: true, marker_options: {
            startIcon: customIcon,
            endIcon: customIcon
          }, polyline_options: { color: '#56F536'}})
        .on('loaded', (e: LeafletEvent) => {
          this.map?.fitBounds(e.target.getBounds());
        }).addTo(this.map);
        console.log(leafletGpx.data());`

Am I doing something wrong, is my data not valid or is this a bug?

**Comment by mpetazzoni** [comment]
Your `console.log()` statement will execute immediately, before the `loaded` event fires. You either need to do this within the event handler, or have a mechanism to wait for that event to fire before continuing.

**Comment by javanese84** [comment]
You are absolutely correct! Sorry and thanks!
