### ISSUE TITLE
Get latLng

### ISSUE THREAD

**Issue by strukturart** [mpetazzoni/leaflet-gpx#145]
Hello,

is it possible after loading a gpx file to get an array with the latLng ? I want to use this to determine how close I am to the track.

thank you for reading

**Comment by mpetazzoni** [comment]
Hi @strukturart,

The plugin does not expose an array of the LatLng points, as it also doesn't keep them internally – only temporarily to build the Leaflet.js Polyline. You can get them back from the Polyline layer object though.

Subscribe to the `addline` event: https://github.com/mpetazzoni/leaflet-gpx/blob/main/gpx.js#L575C5-L575C54

It will have a `line` attribute that is the `L.Polyline` object. You can the call `getLatLngs()` on that: https://leafletjs.com/reference.html#polyline-getlatlngs

HTH,
Max

**Comment by strukturart** [comment]
Thank you for your answer, I found a way to get the data. probably with something detour but it works.

https://github.com/strukturart/o.map/blob/294b5754478447ae6dd6e1002436757fe1bc6a31/application/assets/js/module.js#L400

thanks for your plugin.

**Comment by Clearmist** [comment]
## Working example

The `async` option must be true or your events won't be subscribed.

```javascript
const gpxRoute = new L.GPX(gpx, { async: true })
  .on('addline', (event) => {
    console.log(event.line.getLatLngs());

    // Your code here.
  })
  .on('error', (e) => console.error(`Error loading gpx file: ${e.err}`))
  .addTo(map);
```
