### ISSUE TITLE
Multiple gpx files: map fits only on the last GPX

### ISSUE THREAD

**Issue by donostiastudio** [mpetazzoni/leaflet-gpx#148]
Hi there!
I have a map with several GPX files. I would like the map to correctly center on all the tracks after loading. However, it currently centers only on the last uploaded route. You can see it in action here: https://www.abbondantiedozzinali.it/fondo-stradale/ghiaia/

Here's the code:

`<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
		  <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
		  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-gpx/1.4.0/gpx.min.js"></script>
		  <style>
			#map { height: 500px; }
		  </style>
		<div class="container">
			
		<div id="map" class="bottom30"></div>
		</div>
		
		<script>
			var map = L.map('map').setView([41.90, 12.49], 7); // Imposta la posizione iniziale della mappa
		
			L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
			  attribution: '© OpenStreetMap contributors'
			}).addTo(map);
		
			// Array di percorsi GPX
			var gpxFiles = [
			  // Inserisci qui i percorsi GPX
			  				'https://www.abbondantiedozzinali.it/wp-content/uploads/2020/07/2020-07-29_228758751_Via-Verde-dei-Trabocchi-da-Pescara-a-San-Salvo.gpx',
			  				'https://www.abbondantiedozzinali.it/wp-content/uploads/2020/07/2019-09-09_94274627_Pantelleria-4.gpx',
			  				'https://www.abbondantiedozzinali.it/wp-content/uploads/2016/12/1Romavelletri.gpx',
			  				'https://www.abbondantiedozzinali.it/wp-content/uploads/2015/11/2023-12-29_1402136166_Madonna-di-Morbano.gpx',
			  				'https://www.abbondantiedozzinali.it/wp-content/uploads/2015/11/2023-12-29_1402129035_INsugherata.gpx',
			  				'https://www.abbondantiedozzinali.it/wp-content/uploads/2015/08/2023-12-28_1401931659_Ciclovia-dei-laghi.gpx',
			  				'https://www.abbondantiedozzinali.it/wp-content/uploads/2015/08/2023-12-28_1401929058_Cascate-di-San-Giuliano.gpx',
			  				'https://www.abbondantiedozzinali.it/wp-content/uploads/2015/08/route813453081-1.gpx',
			  				'https://www.abbondantiedozzinali.it/wp-content/uploads/2015/08/subiacolivata.gpx',
			  				'https://www.abbondantiedozzinali.it/wp-content/uploads/2014/03/Anguillara_CanaleMonterano-1.gpx',
			  				'https://www.abbondantiedozzinali.it/wp-content/uploads/2014/03/2023-12-24_1397609329_Lago-di-Martignano.gpx',
			  		
			];
		
			// Carica e visualizza tutti i file GPX sulla mappa
			gpxFiles.forEach(function(gpxFile) {
			  new L.GPX(gpxFile, {
				async: true,
				polyline_options: {
					  color: '#683600',
					  opacity: 0.75,
					  weight: 5,
					  lineCap: 'round'
					  },
				gpx_options: {
					joinTrackSegments: true
				  },	  
				marker_options: {
				 startIconUrl: 'https://www.abbondantiedozzinali.it/wp-content/themes/aed2/images/partenza.svg',
				 endIconUrl: 'https://www.abbondantiedozzinali.it/wp-content/themes/aed2/images/partenza.svg',
				 shadowUrl: ''
				}
			  }).on('loaded', function(e) {
				var gpxLayer = e.target;
				map.fitBounds(gpxLayer.getBounds()); // Centra la mappa sui percorsi GPX
			  }).addTo(map);
			});
		  </script>`

Could you help me?
Thank you

**Comment by mpetazzoni** [comment]
You'll want to extend the bounds each time, instead of fitting to the latest loaded layer's bounds:

```js
var bounds = null;

...
  .on('loaded', function(e) {
    var layerBounds = e.target.getBounds();
    if (bounds === null) {
      bounds = layerBounds;
    } else {
      bounds.extend(layerBounds);
    }
    map.fitBounds(bounds);
  });
```

**Comment by donostiastudio** [comment]
Thank you. Could you help me with the code? I'm not very good at JavaScript. I tried to fix the code as you see below, but it's not working. The map no longer displays the GPX files

`<script>
			var map = L.map('map').setView([41.90, 12.49], 7); // 
			var bounds = null;
			
			L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
			  attribution: '© OpenStreetMap contributors'
			}).addTo(map);
		
			// Array GPX files
			var gpxFiles = [
			  // Inserisci qui i percorsi GPX
			  <?php foreach ($files_gpx as $file_gpx) { ?>
				'<?php echo $file_gpx;?>',
			  <?php } ?>		
			];
		
			// loads gpx files
			gpxFiles.forEach(function(gpxFile) {
			  new L.GPX(gpxFile, {
				async: true,
				polyline_options: {
					  color: '#683600',
					  opacity: 0.75,
					  weight: 5,
					  lineCap: 'round'
					  },
				gpx_options: {
					joinTrackSegments: true
				  },	  
				marker_options: {
				 startIconUrl: '<?php echo get_stylesheet_directory_uri(); ?>/images/partenza.svg',
				 endIconUrl: '<?php echo get_stylesheet_directory_uri(); ?>/images/partenza.svg',
				 shadowUrl: ''
				}
			  }).on('loaded', function(e) {
				  var layerBounds = e.target.getBounds();
				  if (bounds === null) {
					bounds = layerBounds;
				  } else {
					bounds.extend(layerBounds);
				  }
				  map.fitBounds(bounds);
				});
				
			});
		  </script>`

**Comment by mpetazzoni** [comment]
Any javascript errors in the console? Can you confirm the `loaded` event handler is being called (by debugging, or adding a `console.log(...)` statement) ?

**Comment by donostiastudio** [comment]
Thank you so much for your help. I've put WordPress in debug mode. In the console, I'm getting these alerts, but I don't seem to see any errors.

As you can see, with the modification I made trying to follow your instructions, the map is loaded but there are no GPX tracks. Did I modify the code correctly?

THX!

<img width="1373" alt="Screenshot 2024-01-03 alle 09 11 20" src="https://github.com/mpetazzoni/leaflet-gpx/assets/15031297/e6441430-3f13-41db-acf8-3a9fff61322a">

**Comment by mpetazzoni** [comment]
I'd recommend you use the Javascript debugger in your browser with a breakpoint in the `loaded` event handler, and step-by-step through it to see what happens.

**Comment by donostiastudio** [comment]
Hi there! thank you
I solved. This is the working code

` <script>
			 
			  // Creazione della mappa Leaflet
				 var map = L.map('map').setView([41.90, 12.49], 5); // Imposta la posizione iniziale della mappa
			 
				 L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
				   attribution: '© OpenStreetMap contributors'
				 }).addTo(map);
			  
			  // Creazione di un layer per le tracce GPX
			  var gpxLayer = L.geoJson().addTo(map);
			  
			  // Funzione da eseguire quando tutte le tracce GPX sono caricate
			  function onAllGpxLoaded() {
				map.fitBounds(gpxLayer.getBounds()); // Centra la mappa sui percorsi GPX
			  }
			  
			  // Array contenente i percorsi dei file GPX
			  // Array di percorsi GPX
				var gpxFiles = [
				  // Inserisci qui i percorsi GPX
				  <?php foreach ($files_gpx as $file_gpx) { ?>
					'<?php echo $file_gpx;?>',
				  <?php } ?>		
				];
			 
			  
			  // Contatore per tenere traccia del caricamento dei file GPX
			  var gpxCount = 0;
			  
			  // Funzione per caricare i file GPX sulla mappa
			  function loadGPX(file) {
				new L.GPX(file, {
				  async: true,
				  polyline_options: {
						color: '#683600',
						opacity: 0.75,
						weight: 5,
						lineCap: 'round'
						},
				  gpx_options: {
					  joinTrackSegments: true
					},	
				  marker_options: {
				   startIconUrl: '<?php echo get_stylesheet_directory_uri(); ?>/images/partenza.svg',
				   endIconUrl: '<?php echo get_stylesheet_directory_uri(); ?>/images/partenza.svg',
				   shadowUrl: ''
				  }
				}).on('loaded', function(e) {
				  gpxLayer.addLayer(e.target);
				  gpxCount++;
			  
				  // Verifica se tutti i file GPX sono stati caricati
				  if (gpxCount === gpxFiles.length) {
					onAllGpxLoaded(); // Esegui la funzione quando tutti i file sono stati caricati
				  }
				}).addTo(map);
			  }
			  
			  // Carica tutti i file GPX
			  gpxFiles.forEach(function(file) {
				loadGPX(file);
			  });
			  
			</script>`
			
See it in action https://www.abbondantiedozzinali.it/fondo-stradale/ghiaia/

**Comment by donostiastudio** [comment]
I fixed it
this is the working code

<script>
			 
			  // Leaflet Map Creation
				 var map = L.map('map').setView([41.90, 12.49], 5); // Set initial map position
			 
				 L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
				   attribution: 'Abbondanti e Dozzinali'
				 }).addTo(map);
			  
			  // Creating a layer for GPX tracks
			  var gpxLayer = L.geoJson().addTo(map);
			  
			  // Function to be executed when all GPX tracks are loaded
			  function onAllGpxLoaded() {
				console.log(gpxLayer);				
				map.fitBounds(gpxLayer.getBounds()); // Centre the map on GPX routes
			  }
			  
			  // Array containing GPX file paths
				var gpxFiles = [				  
				  <?php foreach ($files_gpx as $file_gpx) { ?>
					'<?php echo $file_gpx;?>',
				  <?php } ?>		
				];
				
				// Array containing related permalinks
				var urls = [
					  
					  <?php foreach ($urls as $url) { ?>
						'<?php echo $url;?>',
					  <?php } ?>		
					];
			 
			  
			  // Counter to keep track of GPX file loads
			  var gpxCount = 0;
			  
			 // Function for loading GPX files onto the map
			 function loadGPX(file, url) {
			   new L.GPX(file, {
				 async: true,
				 polyline_options: {
				   color: '#683600',
				   opacity: 0.75,
				   weight: 5,
				   lineCap: 'round'
				 },
				 gpx_options: {
				   joinTrackSegments: true
				 },
				 marker_options: {
				   startIconUrl: '<?php echo get_stylesheet_directory_uri(); ?>/images/partenza.svg',
				   endIconUrl: '<?php echo get_stylesheet_directory_uri(); ?>/images/partenza.svg',
				   shadowUrl: ''
				 }
			   }).on('loaded', function (e) {
				 gpxLayer.addLayer(e.target);
				 gpxLayer.url = url; // Associating the URL with the GPX layer
			 
				 gpxLayer.on('click', function () {
				   if (gpxLayer.url) {
					 window.open(gpxLayer.url); // Open the associated URL in a new tab/window when the GPX layer is clicked
				   }
				 });
			 
				 gpxLayer.addTo(map);
				 gpxCount++;
				// console.log(gpxCount);
				 
			 
				 // Check if all GPX files have been uploaded
				 if (gpxCount === gpxFiles.length) {					 
				   onAllGpxLoaded(); // Run the function when all files have been loaded
				 }
			   });
			 }
			 
			 // Load all GPX files with their respective URLs
			 gpxFiles.forEach(function (file, index) {
			   var url = urls[index] || ''; // Retrieve the corresponding URL from the "urls" array
			   loadGPX(file, url);
			 });
			 
			  
			  
			  
			</script>
