### ISSUE TITLE
Make gpx tracks clickable

### ISSUE THREAD

**Issue by donostiastudio** [mpetazzoni/leaflet-gpx#149]
Hi
I have another task to solve for a project I have already written about here.

I'm on wordpress, there is a custom taxonomy term archive template. it's in PHP
the map is generated by extracting the gpx files found on each post into an additional dedicated ACF field. 
As you can see everything works https://www.abbondantiedozzinali.it/cialtroni/berny/

I would need to make the tracks clickable and link back to the single post. So if the user clicks on a track, he can see the related post.
I have already set up a variable with the array of all permalinks. I don't know how to make the individual tracks clickable. I don't know how to write the code.
Can you help me?

`<?php
	
	
	$args = array(
		
		'post_type' => 'any',
		$obj->taxonomy => $obj->slug
	 );
	$about = new WP_Query( $args );
	if ( $about->have_posts() ) : ?>
	
	<?php while ( $about->have_posts() ) : $about->the_post(); ?>
	
	<?php if( get_field('gpx') ): ?>
	<?php $files_gpx[] = get_field('gpx'); ?>
	<?php $urls[] = get_permalink();?>
	<?php endif; ?>
	
	<?php endwhile; ?>
	
	<?php
	endif; 
	wp_reset_query(); 
	?>
	
	<?php if (!empty($files_gpx)) { ?>
		  
		  
		  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
			<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-gpx/1.4.0/gpx.min.js"></script>
			<style>
			  #map { height: 500px; }
			</style>
		  <div class="container">
			  
		  <div id="map" class="bottom30"></div>
		  </div>
		  
		  <script>
			 
			  // Leaflet Map Creation
				 var map = L.map('map').setView([41.90, 12.49], 5); // Set initial map position
			 
				 L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
				   attribution: 'Abbondanti e Dozzinali'
				 }).addTo(map);
			  
			  // Creating a layer for GPX tracks
			  var gpxLayer = L.geoJson().addTo(map);
			  
			  // Function to be executed when all GPX tracks are loaded
			  function onAllGpxLoaded() {
				map.fitBounds(gpxLayer.getBounds()); // Centre the map on GPX routes
			  }
			  
			  // Array containing GPX file paths
				var gpxFiles = [				  
				  <?php foreach ($files_gpx as $file_gpx) { ?>
					'<?php echo $file_gpx;?>',
				  <?php } ?>		
				];
				
				// Array containing related permalinks
				var urls = [
					  
					  <?php foreach ($urls as $url) { ?>
						'<?php echo $url;?>',
					  <?php } ?>		
					];
			 
			  
			  // Counter to keep track of GPX file loads
			  var gpxCount = 0;
			  
			  // Function for loading GPX files onto the map
			  function loadGPX(file) {
				new L.GPX(file, {
				  async: true,
				  polyline_options: {
						color: '#683600',
						opacity: 0.75,
						weight: 5,
						lineCap: 'round'
						},
				  gpx_options: {
					  joinTrackSegments: true
					},	
				  marker_options: {
				   startIconUrl: '<?php echo get_stylesheet_directory_uri(); ?>/images/partenza.svg',
				   endIconUrl: '<?php echo get_stylesheet_directory_uri(); ?>/images/partenza.svg',
				   shadowUrl: ''
				  }
				}).on('loaded', function(e) {
				  gpxLayer.addLayer(e.target);
				  gpxCount++;
			  
				  // Check if all GPX files have been uploaded
				  if (gpxCount === gpxFiles.length) {
					onAllGpxLoaded(); // Run the function when all files have been loaded
				  }
				}).addTo(map);				
			  }
			  
			  
			  
			
			  
			  // Load all GPX files
			  gpxFiles.forEach(function(file) {
				loadGPX(file);
			  });
			  
			  
			  
			</script>
		  
		  
		  
		  <?php } ?>
`

**Comment by mpetazzoni** [comment]
You can attach a `click` event handler to the GPX line layer. You can get those by listening to the `addline` events from leaflet-gpx.

You should change the `loadGPX()` function to take both the GPX file URL and the desired target URL:

```js
function loadGPX(gpxUrl, targetUrl) {
  new L.GPX(gpxUrl, ...)
    .on('addline', function(e) {
      e.line.on('click', function() {
        location.href = targetUrl;
      });
    })
    ...
}
```

**Comment by donostiastudio** [comment]
Thank you! I solved with your help and now it works: https://www.abbondantiedozzinali.it/cialtroni/berny/
Last task: fitBounds function doesn't works now

here's my code
console screenshot in attachment

last little help please 🙂

`<script>
			 
			  // Leaflet Map Creation
				 var map = L.map('map').setView([41.90, 12.49], 5); // Set initial map position
			 
				 L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
				   attribution: 'Abbondanti e Dozzinali'
				 }).addTo(map);
			  
			  // Creating a layer for GPX tracks
			  var gpxLayer = L.geoJson().addTo(map);
			  
			  // Function to be executed when all GPX tracks are loaded
			  function onAllGpxLoaded() {
				map.fitBounds(gpxLayer.getBounds()); // Centre the map on GPX routes
			  }
			  
			  // Array containing GPX file paths
				var gpxFiles = [				  
				  <?php foreach ($files_gpx as $file_gpx) { ?>
					'<?php echo $file_gpx;?>',
				  <?php } ?>		
				];
				
				// Array containing related permalinks
				var urls = [
					  
					  <?php foreach ($urls as $url) { ?>
						'<?php echo $url;?>',
					  <?php } ?>		
					];
			 
			  
			  // Counter to keep track of GPX file loads
			  var gpxCount = 0;
			  
			 // Function for loading GPX files onto the map
			 function loadGPX(file, url) {
			   new L.GPX(file, {
				 async: true,
				 polyline_options: {
				   color: '#683600',
				   opacity: 0.75,
				   weight: 5,
				   lineCap: 'round'
				 },
				 gpx_options: {
				   joinTrackSegments: true
				 },
				 marker_options: {
				   startIconUrl: '<?php echo get_stylesheet_directory_uri(); ?>/images/partenza.svg',
				   endIconUrl: '<?php echo get_stylesheet_directory_uri(); ?>/images/partenza.svg',
				   shadowUrl: ''
				 }
			   }).on('loaded', function (e) {
				 var gpxLayer = e.target;
				 gpxLayer.url = url; // Associating the URL with the GPX layer
			 
				 gpxLayer.on('click', function () {
				   if (gpxLayer.url) {
					 window.open(gpxLayer.url); // Open the associated URL in a new tab/window when the GPX layer is clicked
				   }
				 });
			 
				 gpxLayer.addTo(map);
				 gpxCount++;
				// console.log(gpxCount);
				 
			 
				 // Check if all GPX files have been uploaded
				 if (gpxCount === gpxFiles.length) {
				   onAllGpxLoaded(); // Run the function when all files have been loaded
				 }
			   });
			 }
			 
			 // Load all GPX files with their respective URLs
			 gpxFiles.forEach(function (file, index) {
			   var url = urls[index] || ''; // Retrieve the corresponding URL from the "urls" array
			   loadGPX(file, url);
			 });
			 
			  
			  
			  
			</script>
<img width="752" alt="Screenshot 2024-01-07 alle 09 51 32" src="https://github.com/mpetazzoni/leaflet-gpx/assets/15031297/fc55ef91-e047-4e11-a3c1-cac3d9986c8d">
`

**Comment by donostiastudio** [comment]
I'm also able to show you the gpxLayer object
<img width="1006" alt="Screenshot 2024-01-08 alle 16 33 03" src="https://github.com/mpetazzoni/leaflet-gpx/assets/15031297/79a44504-4a1c-4e88-ad0a-b66090c48aee">
