### ISSUE TITLE
Expose points coordinates

### ISSUE THREAD

**Issue by stefanocudini** [mpetazzoni/leaflet-gpx#15]
Assuming that the gpx file is always composed of a single line.
How can I get the coordinates of the last point on the track?

**Comment by PhilWhitehurst** [comment]
Be nice it it created say distance markers every 10km or so via an optional parameter. I use this plugin for a live tracking site and showing distance markers rather calculating distance every tracker update would be great,

**Comment by adoroszlai** [comment]
@PhilWhitehurst This plugin does something like that: https://github.com/adoroszlai/leaflet-distance-markers/

**Comment by mpetazzoni** [comment]
Distance markers will be handled by #65. I don't plan on exposing points coordinates otherwise (as discussed this would require keeping them all in memory, which I don't want the GPX layer to do).
