### ISSUE TITLE
Lazy loading large GPX track only when layer is enabled

### ISSUE THREAD

**Issue by centic9** [mpetazzoni/leaflet-gpx#150]
I would like to create a map which can visualize a fairly large GPX track. 

It is an optional layer, added via a L.control.layers so users can choose to view it if needed:

```
var gpx = new L.GPX(gpxFile, { ... }

L.control.layers(baseLayers, {
'Track': gpx
}).addTo(map);
```

This way the GPX track is not visible initially.

It seems the plugin still fully loads the GPX file at initial loading of the page, even though the track is not shown unless a user selects it in the top-right menu.

Is there a way to lazy-load things here so that the large download is only done when needed?

**Comment by centic9** [comment]
After digging a bit into the source-code, I came up with the following, which seems to work for me:

```
var gpx = new L.GPX(null, {
	async: true
	}
}).on('add', function() {
    console.log('GPX Layer added');
    gpx._gpx = gpxFile;
    gpx.reload();
});
```

Feels a bit "dirty" to overwrite the "_gpx" this way, a new method "reload(gpx)" would make this available as part of the interface nicely.

**Comment by mpetazzoni** [comment]
I wonder if you could use a layer group in your layer control, and dynamically add the map layer to that layer group?

```js
var lg = L.LayerGroup([]).on('add', function(e) {
  var gpx = new L.GPX(gpxFile, {async: true}).on('loaded', ...);
  e.target.addLayer(gpx);
});
L.control.layers(baseLayers, lg).addTo(map);
```

**Comment by centic9** [comment]
Thanks, seems to work as well, only necessary change from your suggestion was to use `new L.LayerGroup([])`.
