### ISSUE TITLE
ES Module

### ISSUE THREAD

**Issue by mjpoo** [mpetazzoni/leaflet-gpx#155]
Hi @mpetazzoni 
Do you know if leaflet-gpx is available as an ES Module (rather than UMD)?
The reason I ask is because I would like to use it efficiently in Angular.
Many thanks,
Mike

**Comment by mpetazzoni** [comment]
Not yet – I'm not sure how best to support both use cases. You can see https://github.com/mpetazzoni/leaflet-gpx/issues/153 for a related discussion. I'll close this issue as duplicate.

**Comment by mjpoo** [comment]
Many thanks @mpetazzoni, I will keep an eye on developments there. It's worth noting that Leaflet will be ESM rather than ES5 from version 2. A development version is available on their [download page](https://leafletjs.com/download.html).
