### ISSUE TITLE
Cannot disable startIcon or endIcon

### ISSUE THREAD

**Issue by MarsupialFan** [mpetazzoni/leaflet-gpx#158]
According to the `Configuring markers` section in `README.md`:

> startIcon is used for ...
> You can also override any of those to null to disable the corresponding marker altogether.

However, when I set it to null,

```
        const options = {
            async: true,
            markers: {
                startIcon: null,
            },
        };
```

I get the following error message:

> TypeError: Object.entries requires that input parameter not be null or undefined

I suspect this might be due to [lines 298-299 of gpx.js](https://github.com/mpetazzoni/leaflet-gpx/blob/57978e58eecf4fac7fd76f441f92aba9e8757490/gpx.js#L298):
```
      } else if (typeof(value) === 'object') {
        markers[key] = this._prepare_markers(value);
```
Since the key (`startIcon` or `endIcon`) doesn't match the previous `if`'s, and since `null` is an object, the code calls `_prepare_markers` recursively with `null` as the `markers` parameter, and then `Object.entries(markers)` barfs.

Should the code refrain from making the recursive call if `value` is `null`?

[On a separate note, [this issue](https://github.com/mpetazzoni/leaflet-gpx/issues/102) (from 4 years ago) suggests to set `startIconUrl` to `null`, but this no longer works either.]

Thank you!

**Comment by mpetazzoni** [comment]
Thanks! I didn't realize `type(null)` would be `object` 😁 Typical Javascript gotcha! Fixed and released in v2.1.2.
