### ISSUE TITLE
get_elevation_gain

### ISSUE THREAD

**Issue by nicopere** [mpetazzoni/leaflet-gpx#166]
Hello,

Related to [that issue](https://github.com/mpetazzoni/leaflet-gpx/issues/78) but not convinced by the end of it, hence I am proposing it anew. 

In my understanding, `get_elevation_gain()` is basically computing the difference in registered altitude from point to point and adding only the positive ones. I can't understand why this relatively simple computation is giving such discrepancies _on the very same gpx file_ (comparing with [gpx.studio](https://gpx.studio/) in my case).

One example (among others):
- gpx.studio: D+ = 854 m
- get_elevation_gain: D+ = 1105 m

These tracks ([bicycle in Brittany](https://www.lherminet.infini.fr/cyclo/)) have numerous short elevations so I suspect some sort of rounding error...

Currently using leaflet-gpx 1.7.0.

Nicolas

**Comment by mpetazzoni** [comment]
I think it's likely gpx.studio uses a smarter algorithm, with some slight smoothing over a few consecutive points, to mitigate the possible jitter in altitude measurements by GPS – especially on higher recording rates like 1Hz.

**Comment by ChrilleSchappe** [comment]
Computing the elevation gain is a equivalent with the "Coastline Paradox" - so there is no well defined right value!

**Comment by mpetazzoni** [comment]
@ChrilleSchappe Exactly. That's why I didn't bother implementing a more "clever" algorithm here – whatever I chose it would be wrong. So I provide the simplest "here's the sum of all positive deltas".

**Comment by nicopere** [comment]
Thanks guys for your clever answers. 
In the meanwhile I came across [this](https://www.gpsvisualizer.com/tutorials/elevation_gain.html) where the problem is nicely explained for the unawre (like me ;-). Not sure though this is the same numerical issue as computing the length of the (fractal) coastline of, say, Brittany. What is strange: the discrepancy actually increases when replacing GPS measures by gpx.studio's DEM (my GPS data were smoother!). 
I will look into the code of gpx.studio to get an idea of their algorithm (not documented otherwise). 
Cheers,
Nicolas
