### ISSUE TITLE
working with geoJSON

### ISSUE THREAD

**Issue by facultymatt** [mpetazzoni/leaflet-gpx#19]
Does anyone have experience using this with geoJSON? I suspect there are ways to convert geoJSON to CPX files. 

It would a great feature if this plugin supported geoJSON. A specific object format would be great and then different use cases could provide their data into that format. 

For example I have the following data: 

    {
        "time": "2014-05-12T16:55:02+0000",
        "location": {
          "type": "Point",
          "coordinates": [-70.222, 42.123]
        },
        "speed": 5400.0,
        "altitude": 14.67527198791504,
        "tripId": "1399913694471-c258e6ce-667e-4749-a3a4-ae93f00e56a6"
      }

**Comment by mpetazzoni** [comment]
GeoJSON works natively with Leaflet: http://leafletjs.com/reference.html#geojson

That being said, there isn't much relationship with GPX and the objectives of the `leaflet-gpx` plugin. You can have a map with a `L.GPX` layer, and add your own `L.geoJson` layer on it too.
