### ISSUE TITLE
Request: min-max altitude

### ISSUE THREAD

**Issue by tosolini** [mpetazzoni/leaflet-gpx#20]
Hi Mr Petazzoni,
thx for this wonderful plugin. I've a request, is possible to add 2 handlers, like get_elevation_max and get_elevation_min? For hiking is good to show a maxim and minium altitude for a path. Now i can see only elevation gain or loss, is good but not enough.
thank you

**Comment by mpetazzoni** [comment]
You can easily achieve the same thing with:

```javascript
var altitudes = gpx.get_elevation_data.map(function(v) { return v[1]; });
var minEl = Math.min(...altitudes);
var maxEl = Math.max(...altitudes);
```
