### ISSUE TITLE
Distance off by factor 2, route drawn twice

### ISSUE THREAD

**Issue by jolbrich** [mpetazzoni/leaflet-gpx#21]
I have a GPX file which contains data for a "route" three times: as `<wpt>`s, as `<rte>` and as `<trk>` with one `<trkseg>`. If I load and display this file, the same route is drawn twice (darker blue than usual) and the reported `get_distance()` is off by a factor of two, presumably because both `<rtept>`s and `<trkpt>`s are parsed. I 'fixed' this problem for me by removing the `['trkseg', 'trkpt']` bit from the `tags` variable. Would it be possible/worth it to handle this situation automatically?

**Comment by mpetazzoni** [comment]
Well, I guess it depends on how the software that recorded the GPS trace is implemented. It's a little weird that it would the route as both a route and a track at the same time. Usually you get one or the other, not both, so the code was made to read both. Maybe this can be made an option (aka make it possible to select either the plugin should read routes, tracks, or both). Care to give it a shot?

**Comment by jolbrich** [comment]
I'll give it a try.
