### ISSUE TITLE
Request: add pins for waypoints (even if not part of a track)

### ISSUE THREAD

**Issue by KenBW2** [mpetazzoni/leaflet-gpx#23]

**Comment by Jef2i** [comment]
I agree too !
It could really be fine, please.

**Comment by justb4** [comment]
I have made a small extension to gpx.js in order to parse and visualize Waypoints. If needed I can provide a Pull Request. See the updated README and code at https://github.com/justb4/leaflet-gpx.
I have an example running at: http://app.map5.nl/nltopo?gpx=gpx/vliegenbos238.gpx.

**Comment by mpetazzoni** [comment]
I'd love a PR! Don't hesitate to send your contributions

**Comment by basco-johnkevin** [comment]
+1
