### ISSUE TITLE
gpx color displayed

### ISSUE THREAD

**Issue by euri10** [mpetazzoni/leaflet-gpx#27]
hello,
I got a map with several paths, I can't figure how to change the color
any pointers ?
thanks

**Comment by adoroszlai** [comment]
Examples in README.md show usage of `marker_options` for setting properties of marker icons.  Path properties can be similarly specified by `polyline_options`.

```js
new L.GPX(data, {
    async: true,
    marker_options: { startIconUrl: null, endIconUrl: null },
    polyline_options: { color: 'red' }
});

**Comment by mpetazzoni** [comment]
Thanks @adoroszlai !
