### ISSUE TITLE
git tag version

### ISSUE THREAD

**Issue by kennynaoh** [mpetazzoni/leaflet-gpx#32]
Hello @mpetazzoni ,
I am the member in [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
Could you add the git tags in Github?
Thanks.

https://github.com/cdnjs/cdnjs/issues/6746

**Comment by mpetazzoni** [comment]
Oh, cool. I justed tagged the current master as v1.0.0. Thanks!
