### ISSUE TITLE
GPX Tracks

### ISSUE THREAD

**Issue by ALD2355** [mpetazzoni/leaflet-gpx#35]
Thr Leaflet plugin will not import this test gpx.  Does the gpx track have to be formatted differently as I can read it on another gpx add-in? 

Thanks

<?xml version="1.0" encoding="UTF - 8" standalone="no"?>
<gpx
version="1.0"
creator="http : // www.sysmaps.com / "
xmlns:xsi="http : // www.w3.org / 2001 / XMLSchema - instance"
xmlns="http : // www.topografix.com / GPX / 1 / 0"
xsi:schemaLocation="http : // www.topografix.com / GPX / 1 / 0 / gpx.xsd">
<rte>
  <name>WGS84 Route 23/6/2016 11:42:54</name>
<rtept lat="48.373927" lon="10.895176">
<ele>00000000491</ele>
<name>Point 1</name>
<desc>Point 1: Pos: 48.374, 10.895</desc>
</rtept>
<rtept lat="48.372758" lon="10.893116">
<ele>00000000490</ele>
<name>Point 2</name>
<desc>Point 2: Pos: 48.373, 10.893</desc>
</rtept>
<rtept lat="48.372287" lon="10.893996">
<ele>00000000491</ele>
<name>Point 3</name>
<desc>Point 3: Pos: 48.372, 10.894</desc>
</rtept>
<rtept lat="48.371746" lon="10.894232">
<ele>00000000489</ele>
<name>Point 4</name>
<desc>Point 4: Pos: 48.372, 10.894</desc>
</rtept>
<rtept lat="48.371575" lon="10.894897">
<ele>00000000486</ele>
<name>Point 5</name>
<desc>Point 5: Pos: 48.372, 10.895</desc>
</rtept>
<rtept lat="48.371033" lon="10.895004">
<ele>00000000487</ele>
<name>Point 6</name>
<desc>Point 6: Pos: 48.371, 10.895</desc>
</rtept>
<rtept lat="48.370905" lon="10.895691">
<ele>00000000487</ele>
<name>Point 7</name>
<desc>Point 7: Pos: 48.371, 10.896</desc>
</rtept>
<rtept lat="48.370135" lon="10.895927">
<ele>00000000484</ele>
<name>Point 8</name>
<desc>Point 8: Pos: 48.37, 10.896</desc>
</rtept>
<rtept lat="48.369907" lon="10.894403">
<ele>00000000485</ele>
<name>Point 9</name>
<desc>Point 9: Pos: 48.37, 10.894</desc>
</rtept>
<rtept lat="48.369650" lon="10.892794">
<ele>00000000490</ele>
<name>Point 10</name>
<desc>Point 10: Pos: 48.37, 10.893</desc>
</rtept>
<rtept lat="48.368039" lon="10.889275">
<ele>00000000493</ele>
<name>Point 11</name>
<desc>Point 11: Pos: 48.368, 10.889</desc>
</rtept>
<rtept lat="48.367398" lon="10.888953">
<ele>00000000496</ele>
<name>Point 12</name>
<desc>Point 12: Pos: 48.367, 10.889</desc>
</rtept>
<rtept lat="48.366814" lon="10.886786">
<ele>00000000490</ele>
<name>Point 13</name>
<desc>Point 13: Pos: 48.367, 10.887</desc>
</rtept>
<rtept lat="48.366015" lon="10.887322">
<ele>00000000488</ele>
<name>Point 14</name>
<desc>Point 14: Pos: 48.366, 10.887</desc>
</rtept>
</rte>
</gpx>

**Comment by mro** [comment]
That's correct, your example is no GPX. You can validate with

    $ xmllint --schema http://www.topografix.com/GPX/1/1/gpx.xsd my-gpx-document.gpx

**Comment by ALD2355** [comment]
Thanks for the reply.  I have put the file through gpsies to convert it.

 

Regards

 

Alastair Day

 

 

Reduce / Reuse / Recycle: Please Print Only if Necessary 

 

Von: Marcus Rohrmoser [mailto:notifications@github.com] 
Gesendet: 23 June 2016 12:31
An: mpetazzoni/leaflet-gpx <leaflet-gpx@noreply.github.com>
Cc: ALD2355 <aday@system.co.uk>; Author <author@noreply.github.com>
Betreff: Re: [mpetazzoni/leaflet-gpx] GPX Tracks (#35)

 

That's correct, your example is no GPX. You can validate with

$ xmllint --schema http://www.topografix.com/GPX/1/1/gpx.xsd my-gpx-document.gpx
