### ISSUE TITLE
Is there a way to add a marker for every 1 km/ mile?

### ISSUE THREAD

**Issue by binderup** [mpetazzoni/leaflet-gpx#39]
I would like to use Leafletjs and your plugin for our running club, and I have both leafletjs and your plugin running - I would like however to be able to display a numbered marker for every 1 km along the track.

Is this possible with Leafletjs and (or) your plugin?

**Comment by mpetazzoni** [comment]
It's not possible out of the box right now, but I'd be interested in having such a feature too if you feel like implementing it. The easiest way would be, as you go through the datapoints, to place a marker on each point after the accumulated distance so far goes over the next km/mi.

**Comment by soulseekah** [comment]
This seems relevant https://github.com/adoroszlai/leaflet-distance-markers

**Comment by binderup** [comment]
That was the solution I ended up with.
