### ISSUE TITLE
Show track "name" on marker click

### ISSUE THREAD

**Issue by WACMemphis** [mpetazzoni/leaflet-gpx#41]
Looking at the code, it seems that you can define `marker_options` and set `clickable` to `true`.

However, this doesn't appear to have any effect. I'd ideally want to be able to show the track (`trk`) name and maybe even more information about the track on mouse click.

Is this already possible? If not, how could this be added?

**Comment by mpetazzoni** [comment]
When the point (marker) is added, an `addpoint` event is fired, with the following event data:

```json
{
  point: p,
  point_type: 'start'
}
```

You should be able to add an event listener and look for the `point_start`, and modify the given point `p`'s options and text bubble.

Let me know if this works, or re-open otherwise.

**Comment by WACMemphis** [comment]
Would you be able to write a small example? I'm not quite sure where to start, i.e. where to register the `addpoint` listener and how to modify the options and text bubble.

**Comment by mpetazzoni** [comment]
Something like this maybe? I haven't tested it.

```javascript
new L.GPX(url, options)
  .on('loaded', function(e) {
    map.fitBounds(e.target.getBounds());
  })
  .on('addpoint', function(e) {
    if (e.data.point_type === 'point_start') {
      e.data.point.bindPopup('This is my track name');
    }
  })
  .addTo(map);
```

**Comment by WACMemphis** [comment]
Thanks! Got it working with some tweaks:

    .on('addpoint', function(e) {
        if (e.point_type === 'start') {
            var text = e.target._info.name;
            text += '<br/>L&auml;nge: ' + e.target._info.length.toFixed(2) + ' m';
            text += '<br/>Anstieg: ' + e.target._info.elevation.gain.toFixed(2) + ' m';
            if(e.target._info.duration.start !== null)
                  text += '<br/>Datum: ' + e.target._info.duration.start.toLocaleDateString();
            e.point.bindPopup(text);
        }
        else if (e.point_type === 'end'){
            map.removeLayer(e.point);
        }
    })

**Comment by Fraasi** [comment]
What are the odds that I found this comment? I wish I had little help six months ago with this.
@WACMemphis  Here's my code with working live example https://github.com/Fraasi/Leaflet-GPX-Map
And thank you to mpetazzoni for a great plugin.
