### ISSUE TITLE
Start-End  icons obscuring map features

### ISSUE THREAD

**Issue by atlbike** [mpetazzoni/leaflet-gpx#44]
Even with a blank, transparent default png a large blank box remains on the map.  I'm plotting multiple maps with common start-end points and the result is 10 overlapping empty boxes that obscure other map features.  I'll log a pull request to add a feature to specify no start-end icons.

Very pleased with the results I've gotten with the extension.
Thank You!

**Comment by atlbike** [comment]
I just added a 'if' block on the end points and set it to false.  Added a boolean in your var declarations.  Didn't try to add a passed parameter.  This fixed my issues, but it might be a useful feature for others.

**Comment by mpetazzoni** [comment]
With the recent changes in v1.2.0 I believe if you pass `startIconUrl: null` and `endIconUrl: null`, it shouldn't attempt to place a marker at all. Could you confirm?

**Comment by atlbike** [comment]
They were generated by gpx.js, I edited the base code.

When I get back to work on the maps I'll test this.


________________________________
