### ISSUE TITLE
[QUESTION] Integrate leaflet-gpx with leaflet-awesome-markers

### ISSUE THREAD

**Issue by yamila-moreno** [mpetazzoni/leaflet-gpx#46]
Hi! I'm using this library for the first time. It's fantastic, thank you very much :D 

I'm having troubles integrating leaflet-gpx marker with leaflet-awesome-markers. My goal is that the startIcon of the gpx can be a font-awesome-icon (with custom icons and so). 

This is the code I'm trying to make work:

```
    var myIcon = L.AwesomeMarkers.icon({
        icon: 'coffee',
        prefix: 'fa',
        markerColor: 'blue',
        iconColor: 'white'
    }); 
    var gpx = new L.GPX(gpx, {
         async: false,
         marker_options: {
                    icon: myIcon,
                    startIconUrl: null,
                    endIconUrl: null,
                    shadowUrl: null
          }     
    }); 
```

Best

**Comment by mpetazzoni** [comment]
Hi! Thanks for the kind words!

I see what you're trying to do, and sadly this is not possible right now, but I could make some changes to make it possible.

Hang tight :)

**Comment by mpetazzoni** [comment]
Done! See the README for instructions and let me know if it works for you!

**Comment by yamila-moreno** [comment]
Hi!! wow! That was quick!! Thank you very much for implementing the feature. It worked like a charm:
https://yamila-moreno.github.io/routes/#5/47.070/4.790

\o/
