### ISSUE TITLE
Layer does not reappear after hidden/shown via layer control

### ISSUE THREAD

**Issue by stefanclark** [mpetazzoni/leaflet-gpx#49]
Recreate:
Load gpx file and add to control
hide layer (untick checkbox) and show layer (tick checkbox)
layer does not reappear... 
`
xxx = new L.GPX('file.gpx', {async: true}).addTo(map);
L.control.layers(null,{'XXX':xxx}).addTo(map)
`

**Comment by mpetazzoni** [comment]
Hmm, I guess I never checked the interaction of layer controls with GPX.js. Is there a specific event that the layer is supposed to handle when being hidden/shown by the layer control?

**Comment by mpetazzoni** [comment]
Hmmm, I just tried this and it works just fine. Do you see any messages in the Javascript console that would indicate a problem? Can you share a more complete code example (and GPX file) that I could try out?

I've updated the demo at http://mpetazzoni.github.io/leaflet-gpx/ so you can see it in action for yourself.

**Comment by stefanclark** [comment]
My mistake.  I was using a non-standard GPX file with multiple routes (<rte></rte>) which loads fine initially, but breaks in this case.

**Comment by mpetazzoni** [comment]
No worries. Is multiple routes in the GPX file something that's supported by the official spec? Is this something that this plugin should handle better?

**Comment by stefanclark** [comment]
I've checked spec and multiple routes are allowed:
http://www.topografix.com/gpx/1/1/gpx.xsd
```xml
<xsd:element name="rte" type="rteType" minOccurs="0" maxOccurs="unbounded">
<xsd:annotation>
<xsd:documentation>A list of routes.</xsd:documentation>
</xsd:annotation>
</xsd:element>`

**Comment by mpetazzoni** [comment]
Any change you can share your GPX file? I'm still unable to reproduce the problem even when having multiple routes in my source GPX.
