### ISSUE TITLE
wptIcons is missing in _DEFAULT_MARKER_OPTS 

### ISSUE THREAD

**Issue by mbretter** [mpetazzoni/leaflet-gpx#53]
Hi,

the wptIcons property is missing in the _DEFAULT_MARKER_OPTS, this leads to a js error if marker_options are specified without wptIcons and GPX track contains waypoints.

cheers,

**Comment by mpetazzoni** [comment]
Oh, turns out this is already fixed by #50, but there was no release made with the fix. I just pushed v1.3.1.
