### ISSUE TITLE
Question: Editing GPX

### ISSUE THREAD

**Issue by citizenfish** [mpetazzoni/leaflet-gpx#56]
Could the GPX be edited by a draw control for example [https://github.com/Leaflet/Leaflet.draw](url).

I tried the following code but it did not appear to work. The GPX displays fine but the draw control cannot edit it?

```
var gpxLayer = new L.GPX(gpx, {async: true});
        gpxLayer.on('loaded', function(e) { map.fitBounds(e.target.getBounds());}); 
        map.addLayer(gpxLayer);

    var options = {
        position: 'topleft',
        draw : {
            polygon: false,
            circle: false,
            rectangle: false,
            marker: false,
            line: false
        },

        edit: {
            featureGroup: gpxLayer,
            remove: false
        }
    };

    var drawControl = new L.Control.Draw(options);
    map.addControl(drawControl);
```

**Comment by mpetazzoni** [comment]
I must say I've never tried this. If there is a way to make it work, keep in mind that all the metadata information calculated by leaflet-gpx is done when reading/parsing the original GPX file, so none of that information will be accurate once you start editing the features directly.
