### ISSUE TITLE
Support for multiple GPX tracks from the same file

### ISSUE THREAD

**Issue by julienappert** [mpetazzoni/leaflet-gpx#60]
Hi and thank you for your wonderful job.

I have some GPX files with two tracks inside. When I load them with your plugin, I have only one line drawn on the map, instead of two. That is odd because points of two tracks should not be connected.

What do you think ?

**Comment by mpetazzoni** [comment]
Yeah, there isn't really a concept of multiple distinct tracks implemented in the library. I also don't remember what the behavior is for multiple track segments within a given track.

The main issue here will be backwards compatibility, if we have to introduce a logical "track" construct when using the various functions of the plugin like `get_distance()`, etc. Or maybe you should be using different, distinct `L.GPX` layers, and we add the ability to select which track from the input GPX to use in a layer?

Open to suggestions.

**Comment by gegeweb** [comment]
Hi,

I think there is two situations.

The first one is a long jouney with steps, so we want to be able to concatenate these in one trace (line) and concatenate data (total times, average speed, total distance), but we probably want to extract individual data for each steps.

The second one is a event or course where each tracks is a variant of the route.
In this case we don't want to concatenate data but we want each tracks as an unique track.

Perhaps an option to indicate if we want concatenate data (but isolate tracks to) or have each tracks as unique. 

(sorry for my english…)
