### ISSUE TITLE
Question  regarding preview gpx on marker hover

### ISSUE THREAD

**Issue by NiekRood** [mpetazzoni/leaflet-gpx#62]
I have a question regarding leaflet-gpx.

I am using Leaflet.markercluster for displaying many routes.  What I am trying to achieve is that if a user 'mouse-over' an marker the GPX track is shown.

My code for displaying the clustering is:
```javascript
    var markers = L.markerClusterGroup();
    for (var i = 0; i < markers_var.length; i++) {
        var a = markers_var[i];
        var title = a[3];
        var gpxfile= a[2];
  ` 
        var marker = L.marker(new L.LatLng(a[0], a[1]), {
        
            title: title
        });
      
        marker.bindPopup(title);
        markers.addLayer(marker);
  

        marker.on('mouseover', function (e)
{
*********How can I get the GPX (this is  **gpxfile= a[2];**  displayed?*******
  });

**Comment by mpetazzoni** [comment]
You should probably just have the GPX layers created and loaded, but not added to the map yet, and simply do the `map.addLayer()` on mouseover and `map.removeLayer()` on mouseout. If you have a large number of GPX layers you'll probably want to lazy-load them though.
