### ISSUE TITLE
loaded event not firing

### ISSUE THREAD

**Issue by quilkin** [mpetazzoni/leaflet-gpx#66]
I tried running the simple example in the readme, and also tried copying your demo file to my system (and to my remote site). In all cases the 'loaded' event of new 'L.GPX' doesn't get fired (I debugged with Chrome, and Firefox). Tried with my own gpx file and your demo one, all in same folder as index.html -  same result each time. Yet it clearly does get fired when I run the demo on your own site.
Clearly I'm doing something fundamentally wrong but I can't see what!

**Comment by mpetazzoni** [comment]
Can you share your code? What's serving your GPX file?

**Comment by mpetazzoni** [comment]
Is it actually making the request for the GPX file correctly in that situation, and loading the file? As in, is it a load issue, or an event issue?

**Comment by rtransat** [comment]
I think it's a duplicate https://github.com/mpetazzoni/leaflet-gpx/issues/24

I have the same issue. The event is never fired.
