### ISSUE TITLE
Impossible to load not well-formed GPX

### ISSUE THREAD

**Issue by VladimirKalachikhin** [mpetazzoni/leaflet-gpx#69]
I want to show on the map a GPX, which is being recorded right now. This GPX does not have closing tags, of course. So I have a "XML Parsing Error: no root element found".

**Comment by mpetazzoni** [comment]
I don't think handling this use case necessarily belongs at this layer. You should be feeding correct GPX data to `leaflet-gpx`, for example by concatenating the appropriate closing tags before passing the GPX content in:

```javascript
var gpx = '...'; // assuming you're accumulating GPX data into this string
new L.GPX(gpx + '</trkseg></trk></gpx>', ...);
```
