### ISSUE TITLE
Make sure that the start pin is always above the other waypoints

### ISSUE THREAD

**Issue by delitestudio** [mpetazzoni/leaflet-gpx#70]
Hello and thanks for this great plugin!

Is there a way to make sure the start pin is always above the other waypoints?

**Comment by mpetazzoni** [comment]
Absolutely!

This plugin fires an event for every marker/pin that is added to the map. When the start pin is added, you'll get a `addpoint` event with a `point_type: 'start'` in the event payload, as written at https://github.com/mpetazzoni/leaflet-gpx/blob/master/gpx.js#L339.

This event payload includes the pin object itself, and you can call `.setZIndexOffset(...)` on it, as documented here: https://leafletjs.com/reference-1.3.0.html#marker-setzindexoffset

So you should be able to write something like this:

```javascript
L.GPX(url, {async: true}).on('addpoint', function(e) {
  if (e.point_type === 'start') {
    e.point.setZIndexOffset(1000);
  }
});
```

**Comment by delitestudio** [comment]
Thank you very much for your detailed answer!
