### ISSUE TITLE
reload() error?

### ISSUE THREAD

**Issue by copilador** [mpetazzoni/leaflet-gpx#76]
Hi. The function gpx.reload() in setInterval  "(setInterval(function() {  gpx.reload();}, 3000); " only works the first cycle, then runs continuously, is an error in my code? Thank you

**Comment by niyasrahman** [comment]
Try This
`let gpxLayer = new L.GPX(gpx, { async: true }).on('loaded', function (e) {
      map.fitBounds(e.target.getBounds());
  }).addTo(map);

       setInterval(function () {
            gpxLayer.reload();
       }, 5000);`
