### ISSUE TITLE
2 GPX tracks with diferent color polylines

### ISSUE THREAD

**Issue by GaRit22** [mpetazzoni/leaflet-gpx#81]
How can I put in 2 GPX tracks with both a diferent polyline color

Thank You,

Gert

**Comment by mpetazzoni** [comment]
Two options: https://github.com/mpetazzoni/leaflet-gpx#line-styling

* Use the GPX Style extension to define the style of each line in the GPX file itself
* Use on `L.GPX` layer for each GPX track on set appropriate `polyline_options` in each
