### ISSUE TITLE
Custom size for wpt

### ISSUE THREAD

**Issue by southmedia** [mpetazzoni/leaflet-gpx#94]
Hi team,

Thank you for your work with this great plugin. I'm building a trekking map and want to identify each track with a different icon mapped from GPX "sym" data. That was ok, but I would like to custom set the size of the wpt icon (green in the middle of the track) and I could´t, after trying in many ways. Can you help me with that? Thank you!!!! Hernán

[http://southmedia.com.ar/mapselchaltentrekking/test-wpt.html](url)

![Trekking Map](https://user-images.githubusercontent.com/12905698/84580539-267f1980-adae-11ea-9183-9976523484c1.png)

Here is where I´m trying to set different color wpt icons:

		// Load GPX Tacks
		
			var tracks = [
				["/mapselchaltentrekking/maps/gpx/track-20.gpx", "#f48024", "4", "", "", ""],
				["/mapselchaltentrekking/maps/gpx/test-wpticon.gpx", "#f48024", "4", "", "", ""],
			];
					
			function loadGpx(item, index) {
				var g = new L.GPX(item[0], { 
					async: true,
					parseElements: ['track'],
					polyline_options: {
						weight: item[2],
						color: item[1],
						fillOpacity: 1
					},
					marker_options: {
						startIconUrl: item[4],
						endIconUrl: item[5],				
						iconSize: [40, 40],
						iconAnchor: [20, 40],
						shadowSize: [0, 0],
						shadowAnchor: [0, 0],
						wptIconUrls: {
						'green': '/mapselchaltentrekking/maps/iconos/sendero-green.png',
 						}
					}
				});						
						

				g.on('loaded', function(e) {
					var gpx = e.target,
					name = gpx.get_name(),
					distM = gpx.get_distance(),
					distKm = distM / 1000,
					distKmRnd = distKm.toFixed(1),
					eleGain = gpx.get_elevation_gain().toFixed(0),
					eleLoss = gpx.get_elevation_loss().toFixed(0),
					eleDiff = gpx.get_elevation_max().toFixed(0) - gpx.get_elevation_min().toFixed(0);
					var info = "<b>" + name + "</b></br>" + "Distancia: <b>" + distKmRnd + " km </b></br>" + "Desnivel: <b>" + eleDiff + " m </b></br> <a target=" + "'" + "_parent" + "'" + "href=" + "'" + item[3] + "'"  + ">+ info</a>"

![Trekking Map2](https://user-images.githubusercontent.com/12905698/84580619-e40a0c80-adae-11ea-9264-01c62fe6ab4c.png)

Below is html code:

<!DOCTYPE html>
<html>
    <head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Trekking Map</title>
	
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
	
	

	<link rel="stylesheet" href="/mapselchaltentrekking/maps/style/mapa-general.css" />
	
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
	
	
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.2/dist/leaflet.css" />
	<script src="https://unpkg.com/leaflet@1.3.2/dist/leaflet.js"></script>
	
	
	<script src="https://unpkg.com/leaflet-geometryutil@0.9.1/src/leaflet.geometryutil.js"></script>
	
	
	<script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/Leaflet.fullscreen.min.js'></script>
    <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/leaflet.fullscreen.css' rel='stylesheet' />
    
	
	<script src="https://unpkg.com/d3@4.13.0/build/d3.min.js" charset="utf-8"></script>
	
	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-gpx/1.4.0/gpx.js"></script>
	
	
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet-easybutton@2/src/easy-button.css">
    <script src="https://cdn.jsdelivr.net/npm/leaflet-easybutton@2/src/easy-button.js"></script>
	
    </head>
    <body>
        
	    <div id="map" style="height: 100% !important;"></div>
	    
        
	    <script>
	    
	        // Map Setup
    		var opts = {
	    		map: {
		    		center: [-48.979325, -72.827558],
			    	zoom: 12.5,
    				markerZoomAnimation: false,
	    			zoomControl: true,
	    			attributionControl: false
		    	},
    			
	    		osmLayer: {
				    url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
				    options: {
					    maxZoom: 18,
					    attribution: 'Map data: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
				    }
			    },
			    
			    otmLayer: {
				url: 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
				    options: {
					    maxZoom: 18,
					    attribution: 'Map data: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)',
				    },
			    },
	    
			    layersControl: {
				    options: {
				    	position: 'topright',
				    	collapsed: true,
			    	},
			    },
			    
			    scale: {
			        maxWidth: 100,
			        metric: true,
			        imperial: false,
			    },
			    
			    fullscreenControl: {
			        title: {
                        'false': 'Pantalla Completa',
                        'true': 'Salir de Pantalla Completa'
                     }
			    }
		    };
		    
		    // Define Icons
		    var iconSize = [20, 20];
		    var shadowSize = [34, 34];
			var iconAnchor = [10, 10];
			var shadowAnchor = [17, 17];

			
			var CampIcon = L.icon({
				iconUrl: '/mapselchaltentrekking/maps/iconos/camp.png',
				iconSize: [iconSize[0], iconSize[1]],
				iconAnchor: [iconAnchor[0], iconAnchor[1]],
				shadowUrl: '/mapselchaltentrekking/maps/iconos/icono-shadow.png',
				shadowSize: [shadowSize[0], shadowSize[1]],
				shadowAnchor: [shadowAnchor[0], shadowAnchor[1]]
			});	

			
			var GendaIcon = L.icon({
				iconUrl: '/mapselchaltentrekking/maps/iconos/genda.png',
				iconSize: [iconSize[0], iconSize[1]],
				iconAnchor: [iconAnchor[0], iconAnchor[1]],
				shadowUrl: '/mapselchaltentrekking/maps/iconos/icono-shadow.png',
				shadowSize: [shadowSize[0], shadowSize[1]],
				shadowAnchor: [shadowAnchor[0], shadowAnchor[1]]
			});				
			
			
			var PasointIcon = L.icon({
				iconUrl: '/mapselchaltentrekking/maps/iconos/pasoint.png',
				iconSize: [iconSize[0], iconSize[1]],
				iconAnchor: [iconAnchor[0], iconAnchor[1]],
				shadowUrl: '/mapselchaltentrekking/maps/iconos/icono-shadow.png',
				shadowSize: [shadowSize[0], shadowSize[1]],
				shadowAnchor: [shadowAnchor[0], shadowAnchor[1]]
			});	
	
		    
		// Load GPX Tacks
		
			var tracks = [
				["/mapselchaltentrekking/maps/gpx/track-20.gpx", "#f48024", "4", "", "", ""],
				["/mapselchaltentrekking/maps/gpx/test-wpticon.gpx", "#f48024", "4", "", "", ""],
			];
					
			function loadGpx(item, index) {
				var g = new L.GPX(item[0], { 
					async: true,
					parseElements: ['track'],
					polyline_options: {
						weight: item[2],
						color: item[1],
						fillOpacity: 1
					},
					marker_options: {
						startIconUrl: item[4],
						endIconUrl: item[5],				
						iconSize: [40, 40],
						iconAnchor: [20, 40],
						shadowSize: [0, 0],
						shadowAnchor: [0, 0],
						wptIconUrls: {
						'green': '/mapselchaltentrekking/maps/iconos/sendero-green.png',
 						}
					}
				});						
						

				g.on('loaded', function(e) {
					var gpx = e.target,
					name = gpx.get_name(),
					distM = gpx.get_distance(),
					distKm = distM / 1000,
					distKmRnd = distKm.toFixed(1),
					eleGain = gpx.get_elevation_gain().toFixed(0),
					eleLoss = gpx.get_elevation_loss().toFixed(0),
					eleDiff = gpx.get_elevation_max().toFixed(0) - gpx.get_elevation_min().toFixed(0);
					var info = "<b>" + name + "</b></br>" + "Distancia: <b>" + distKmRnd + " km </b></br>" + "Desnivel: <b>" + eleDiff + " m </b></br> <a target=" + "'" + "_parent" + "'" + "href=" + "'" + item[3] + "'"  + ">+ info</a>"

					// Register popup on click
					gpx.getLayers()[0].bindPopup(info)
					
					// Mouseover Style;
					gpx.getLayers()[0].on('mouseover', function(e) {
						gpx.getLayers()[0].setStyle({
							weight: 4,
							color: '#71a0b4',
							fillOpacity: 0.8,
						});
						gpx.getLayers()[0].bringToFront();
					});
					gpx.getLayers()[0].on('mouseout', function(e) {
						gpx.getLayers()[0].setStyle({
							weight: 3,
							color: item[1],
							fillOpacity: 1
						});
					});
				});
				g.addTo(map);
			};

		// Define Map Elements
			var info = "Name: ";
			var map = new L.Map('map', opts.map);
			var baseLayers = {};
			baseLayers["Base"] = new L.TileLayer(opts.osmLayer.url, opts.osmLayer.options);
			baseLayers["Topografico"] = new L.TileLayer(opts.otmLayer.url, opts.otmLayer.options);
			var controlLayer = L.control.layers(baseLayers, null, opts.layersControl.options);
			var controlFullscreen = new L.Control.Fullscreen(opts.fullscreenControl)
			 
			// Load Map
			L.control.scale(opts.scale).addTo(map);
			controlFullscreen.addTo(map);
			controlLayer.addTo(map);
			L.easyButton('fa-home', function(btn, map){CenterMap(opts.map.center[0], opts.map.center[1], opts.map.zoom);}, 'Centrar').addTo(map);
			map.addLayer(baseLayers["Base"]);
			tracks.forEach(loadGpx);		

		// Load Pop-ups 
				
            var CampLocation = new L.LatLng(-48.999689, -72.838008);
            L.marker(CampLocation, {icon: CampIcon}).addTo(map).bindPopup("Campamento<br><b>Punta Norte</b>");

				               
            var GendaLocation = new L.LatLng(-48.998940, -72.839430);
            L.marker(GendaLocation, {icon: GendaIcon}).addTo(map).bindPopup("Gendarmería<br><b>Punta Norte</b>");			
			
						
            var PasointLocation = new L.LatLng(-48.960076, -72.815826);
            L.marker(PasointLocation, {icon: PasointIcon}).addTo(map).bindPopup("Paso Internacional<br><b>Dos Lagunas</b>");
			
		
	    </script>
    </body>
</html>

**Comment by mpetazzoni** [comment]
Hmm, that's strange, setting `iconSize` in the `marker_options` works for me. And looking at the link you sent, it looks like the green marker is correctly 40x40. What's not working the way you expect?

**Comment by southmedia** [comment]
Hi, thanks for the answer. You´re right, its working!! Sorry, I had been trying for hours and at the end, frustrated and tired, I din´t realize the last code was ok. Thanks, I´m trying to improve with Leaflet and plugins. It is great tool.
