### ISSUE TITLE
GPX not display

### ISSUE THREAD

**Issue by louisJ20** [mpetazzoni/leaflet-gpx#96]
Hello,

I encounter a problem with the plugin. When I start my html page, the gpx isn't display.
What can i do ?

Thanks in advance.

**Comment by mpetazzoni** [comment]
Just saying "it doesn't work for me" isn't helpful. Can you share more information? Are there any errors in the JavaScript console? Can you share the HTML and JavaScript code you are trying to use?

**Comment by davidof1977** [comment]
I have the same problem, i am using angular and the error in the console is 

ERROR TypeError: leaflet__WEBPACK_IMPORTED_MODULE_1__.GPX is not a constructor
    at MapaComponent.initMap (mapa.component.ts:30)
    at MapaComponent.ngOnInit (mapa.component.ts:15)
    at callHook (core.js:4726)
    at callHooks (core.js:4690)
    at executeInitAndCheckHooks (core.js:4630)
    at refreshView (core.js:12013)
    at refreshComponent (core.js:13445)
    at refreshChildComponents (core.js:11716)
    at refreshView (core.js:12051)
    at renderComponentOrTemplate (core.js:12129)

This is my inex.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>OrganizadorRutas</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.6.0/leaflet.css" />
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css"
   integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
   crossorigin=""/>
</head>
<body>
  <app-root></app-root>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.6.0/leaflet.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-gpx/1.5.0/gpx.min.js"></script>
  <script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
  integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
  crossorigin=""></script>

</body>
</html>
