### ISSUE TITLE
leaflet__WEBPACK_IMPORTED_MODULE_1__.GPX is not a constructor

### ISSUE THREAD

**Issue by davidof1977** [mpetazzoni/leaflet-gpx#97]
Hi,

I am trying to show a gpx in the map. And i am getting the following error, i am developing a angular 9 web app.

ERROR TypeError: leaflet__WEBPACK_IMPORTED_MODULE_1__.GPX is not a constructor

I am using 
"leaflet": "1.6.0",
"leaflet-gpx": "^1.5.0",

My index.html page is like this

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>OrganizadorRutas</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
  integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
  crossorigin=""/>
</head>
<body>
  <app-root></app-root>
  <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
  integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
  crossorigin=""></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-gpx/1.5.0/gpx.min.js"></script>
</body>
</html>

Can you help me?

Thx

**Comment by davidof1977** [comment]
Finally i solve my problem.

**Comment by mpetazzoni** [comment]
This seems like an issue with integrating Leaflet into an Angular app that's packaged by webpack. Not something I'm testing for, but I'm also not doing anything specific that would prevent it from working. Glad you figured it out.
