### ISSUE TITLE
TypeError: Cannot read property 'getBounds' of undefined

### ISSUE THREAD

**Issue by dave-4k** [mpetazzoni/leaflet-gpx#99]
This Plugin is incompatible with "Leaflet.Canvas-Markers" https://github.com/eJuke/Leaflet.Canvas-Markers.

Error: TypeError: Cannot read property 'getBounds' of undefined

**Comment by mpetazzoni** [comment]
@dave-4k Can you share more information? A code sample, more details about the setup and error?

**Comment by Hitesh61** [comment]
Because this.map.fitBounds(e.target.getBounds()) before called .addTo(this.map). please check below solution.

    let me = this;
       
    this.polylineRoute = new L.GPX(gpxFilePath, {async: true}).on('loaded', function(e) {
        me.setBoundsMap(e.target.getBounds());
    }).addTo(this.map);
	
    setBoundsMap(data){
	this.map.fitBounds(data);
    }

**Comment by mpetazzoni** [comment]
Thanks @Hitesh61. This is described in the [Usage section of the README](https://github.com/mpetazzoni/leaflet-gpx#usage).
